language: node_js
node_js:
   - "0.10"
notifications:
  recipients:
    - github@ernie.org
  email:
    on_success: aways
    on_failure: always
before_install:
  - curl -L https://cpanmin.us | perl - App::cpanminus
  - ~/perl5/bin/cpanm local::lib
  - ~/perl5/bin/cpanm JSON
  - # Add path to ~/perl5 modules to ~/.bashrc
  - # echo '[ $SHLVL -eq 1 ] && eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bashrc
  - #
  - ~/perl5/bin/cpanm Text::CSV
  - ~/perl5/bin/cpanm Date::Parse
  - ~/perl5/bin/cpanm LWP::Simple
sudo: false
