language: node_js
node_js:
   - "0.10"
notifications:
  recipients:
    - github@ernie.org
  email:
    on_success: aways
    on_failure: always
before_install:
  - yes | perl -MCPAN -e 'install Text::CSV'
  - yes | perl -MCPAN -e 'install Date::Parse'
  - yes | perl -MCPAN -e 'install LWP::Simple'
sudo: false
