#!/bin/bash
#
# amilist
#
# List images in EC2 with caching. All arguments are case-insensitive grep patterns to filter by.
#
# Example:
# amilist suse packer
#
#
api_category="ec2"
api_call="describe-images"
fields="State,ImageId,Name,State,Architecture,OwnerId,KernelId,VirtualizationType"

aws_generic_list "$api_category" "$api_call" "$fields" "$@"
