#!/bin/sh
#
# Given an aws instance name, ssh to it
# 
# Depends on: 
# 1) ~/git/mci/config/distros.yml for usernames
# 2) ~/.ssh/<key name>.pem with ssh private keys named after amazon key name
# 3) cache_run executable
# 4) instance_info_by_name.sh executable

# how long to cache aws info 
CACHE_SECONDS=300

getuserbydistro () 
{ 
    distro="$1";
    egrep --no-filename ^$distro:\|user: ~/git/mci/config/distros.yml* ~/distros.yml* | grep -A 1 ^$distro: | tail -1 | cut -f2 -d: | tr -d " "
}

instance_name="$1"

if [ ! "$instance_name" ] 
then
  echo "usage: $0 <instance_name>"
  exit 2
fi

header=`cache_run $CACHE_SECONDS "instance_info_by_name.sh $instance_name" | head -1`
data=`cache_run $CACHE_SECONDS "instance_info_by_name.sh $instance_name" | tail -1`

# get column numbers
distro_column="`echo \"$header\"  | tr , \\\\n | grep -n distro | cut -f1 -d: `"
dns_column="`echo \"$header\"  | tr , \\\\n | grep -n PublicDnsName | cut -f1 -d: `"
key_column="`echo \"$header\"  | tr , \\\\n | grep -n KeyName | cut -f1 -d: `"

distro="`echo \"$data\" | cut -f$distro_column -d,`"
dns="`echo \"$data\" | cut -f$dns_column -d,`"
key="`echo \"$data\" | cut -f$key_column -d,`"

user=`getuserbydistro "$distro"`

if [ ! "$user" ] 
then
  user=root
fi

ssh -i ~/.ssh/$key.pem $user@$dns
