#!/bin/bash
#
# Given an aws instance name, ssh to it
# 
# Depends on: 
# 1) ~/git/mci/config/distros.yml for usernames
# 2) ~/.ssh/<key name>.pem with ssh private keys named after amazon key name
# 3) cache_run executable
# 4) instance_info_by_name.sh executable

# how long to cache aws info 
CACHE_SECONDS=300

getuserbydistro () 
{ 
    distro="$1";
    egrep --no-filename ^$distro:\|user: ~/git/mci/config/distros.yml* ~/distros.yml* | grep -A 1 ^$distro: | tail -1 | cut -f2 -d: | tr -d " "
}

instance_name="$1"

if echo $instance_name | grep -q @
then
  user=$(echo $instance_name | cut -f1 -d@)
  instance_name=$(echo $instance_name | cut -f2 -d@)
fi

if [ ! "$instance_name" ] 
then
  echo "usage: $0 <instance_name>"
  exit 2
fi

if [ ! "$AWS_SECRET_ACCESS_KEY" -o ! "$AWS_ACCESS_KEY_ID" ]
then
  . ~/amazon-build.sh
fi

header=$(cache_run $CACHE_SECONDS "instance_info_by_name.sh $instance_name" | head -1)
data=$(cache_run $CACHE_SECONDS "instance_info_by_name.sh $instance_name" | tail -1)

# account for weird lost data
#
if [ \( ! "$data" \) -o "$(echo \"$data\" | grep running,\*$)" -o "$data" = "$header" -o "$(echo \"$data\" | grep stopped)" ]
then
  echo "retrying to poll aws data"
  header=$(cache_run 0 "instance_info_by_name.sh $instance_name" | head -1)
  data=$(cache_run $CACHE_SECONDS "instance_info_by_name.sh $instance_name" | tail -1)
fi

# get column numbers
distro_column="$(echo "$header"  | tr , \\n | grep -n distro | cut -f1 -d: )"
dns_column="$(echo "$header"  | tr , \\n | grep -n PublicDnsName | cut -f1 -d: )"
key_column="$(echo "$header"  | tr , \\n | grep -n KeyName | cut -f1 -d: )"

distro="$(echo "$data" | cut -f$distro_column -d,)"
dns="$(echo "$data" | cut -f$dns_column -d,)"
key="$(echo "$data" | cut -f$key_column -d,)"

if [ ! "$dns" -o "$dns" = "running" ]
then
  echo "Can't find dns info for server ($data)"
  exit 3
fi

if [ ! "$user" ]
then
  user=$(getuserbydistro "$distro")
fi

if [ ! "$user" ] 
then
  user=root
fi

ssh -i ~/.ssh/$key.pem $user@$dns
