#!/bin/bash
#
# Given an aws instance name, ssh to it
# 
# Depends on: 
# 1) ~/git/mci/config/distros.yml for usernames
# 2) ~/.ssh/<key name>.pem with ssh private keys named after amazon key name
# 3) cache_run executable
# 4) instance_info_by_name.sh executable

# how long to cache aws info 
CACHE_SECONDS=300

getuserbydistro () 
{ 
    distro="$1";
    egrep --no-filename ^$distro:\|user: ~/git/mci/config*/distros.yml* ~/distros.yml* | grep -A 1 ^$distro: | tail -1 | cut -f2 -d: | tr -d " "
}

instance_name="$1"

if echo $instance_name | grep -q @
then
  user=$(echo $instance_name | cut -f1 -d@)
  instance_name=$(echo $instance_name | cut -f2 -d@)
fi

if [ ! "$instance_name" ] 
then
  echo "usage: $0 <instance_name>"
  exit 2
fi

if [ ! "$AWS_SECRET_ACCESS_KEY" -o ! "$AWS_ACCESS_KEY_ID" ]
then
  . ~/amazon-build.sh
fi

count=$(ec2list running $instance_name | wc -l)
header=$(ec2list | head -1)
data=$(ec2list running $instance_name | tail -1)

if [ "$count" -gt 2 ]
then
  data=$(ec2list ernie running $instance_name | tail -1)
fi


# get column numbers
distro_column="$(echo "$header"  | tr , \\n | grep -nx distro | cut -f1 -d: )"
dns_column="$(echo "$header"  | tr , \\n | grep -nx PublicDnsName | cut -f1 -d: )"
key_column="$(echo "$header"  | tr , \\n | grep -nx KeyName | cut -f1 -d: )"
name_column="$(echo "$header"  | tr , \\n | grep -nx Name | cut -f1 -d: )"

distro="$(echo "$data" | cut -f$distro_column -d,)"
dns="$(echo "$data" | cut -f$dns_column -d,)"
key="$(echo "$data" | cut -f$key_column -d,)"
name="$(echo "$data" | cut -f$name_column -d,)"

if [ ! "$dns" -o "$dns" = "running" ]
then
  echo "Can't find dns info for server ($data)"
  exit 3
fi

if [ ! "$user" ]
then
  user=$(getuserbydistro "$distro")
fi

if [ ! "$user" ] 
then
  user=root
fi

echo connecting to $name
echo "$data"
ssh -i ~/.ssh/$key.pem $user@$dns
