#!/bin/bash
#
# Delete all cache entries from cache_get and cache_run
#
set -o nounset
set -o pipefail
set -o errexit

CACHEDIR=~/.generic_cache/

PATTERN="${1:-}"
find "$CACHEDIR" -name \*"$PATTERN"\* -type f | xargs rm
