#!/bin/bash
#
# ebslist
#
# List Volumes in EC2 with caching. All arguments are case-insensitive grep patterns to filter by.
#
# Example:
# ebslist suse packer
#
#

api_category="ec2"
api_call="describe-volumes"
fields="VolumeId,Size,State,VolumeType,AvailabilityZone"

aws_generic_list "$api_category" "$api_call" "$fields" "$@"
