#!/bin/bash
if [ ! "$AWS_SECRET_ACCESS_KEY" -o ! "$AWS_ACCESS_KEY_ID" ]
then
  . ~/amazon-build.sh
fi

if [ "$1" ]
then
  cache_run 300 "aws ec2 describe-instances | format_aws_json.js $AWS_ACCESS_KEY_ID" | grep -i "$1"
else
  cache_run 300 "aws ec2 describe-instances | format_aws_json.js $AWS_ACCESS_KEY_ID" | grep -i "$1"
fi

