#!/bin/bash
if [ ! "$AWS_SECRET_ACCESS_KEY" -o ! "$AWS_ACCESS_KEY_ID" ]
then
  . ~/amazon-build.sh
fi

tempfile=$(mktemp /tmp/ec2list.XXXXXX)
tempfile2=$(mktemp /tmp/ec2list.XXXXXX)
cache_run 300 "aws ec2 describe-instances | format_aws_json.js" $AWS_ACCESS_KEY_ID > $tempfile
while [ "$1" ]
do
  cat "$tempfile" | grep -i "$1" > "$tempfile2"
  cat "$tempfile2" > "$tempfile"
  shift
done

cat $tempfile

