#!/bin/bash
#
# ec2list
#
# List instances in EC2 with caching. All arguments are case-independent grep patterns to filter by.
#
# Example:
# ec2list running ernie-keypair1 sometagvalue
#
#
if [ ! "$AWS_SECRET_ACCESS_KEY" -o ! "$AWS_ACCESS_KEY_ID" ]
then
  . ~/amazon-build.sh
fi

tempfile=$(mktemp /tmp/ec2list.XXXXXX)
tempfile2=$(mktemp /tmp/ec2list.XXXXXX)

regions=$(cache_run 9999999 "aws ec2 describe-regions  --query Regions[*].RegionName --output text" $AWS_ACCESS_KEY_ID | sed 's/ap-northeast-2//')
printed_header=""
for region in $regions
do
  if [ ! "$printed_header" ]
    then
      cache_run 300 "aws --region $region ec2 describe-instances | format_aws_json.js" $AWS_ACCESS_KEY_ID >> $tempfile &
      printed_header=1
    else
      cache_run 300 "aws --region $region ec2 describe-instances | format_aws_json.js" $AWS_ACCESS_KEY_ID | tail -n +2 >> $tempfile &
    fi
done
wait
while [ "$1" ]
do
  cat "$tempfile" | grep -i "$1" > "$tempfile2"
  cat "$tempfile2" > "$tempfile"
  shift
done

cat $tempfile

