#!/usr/bin/python
#
#
# Types of things to be able to specify:
# # Day
# ## Today (default)
# ## Yesterday
# ## Two days ago (bonus feature)
# # Meal
# ## "current" (default - logic based on time of day)
# ### Time periods should be dynamic
# ## Breakfast / Lunch / Dinner / "Buffer"
# ### Should be dynamic based on configured mfp meals
# # Serving size
# ## Size associated with food item (default if present - if item from meal or history)
# ## Numeric value (default if food not pulled from history)
# # Meal or food item
# ## case insensitive multiple word text search using first found:
# ### Meal
# ### Item from history
# ### Item from database
#
# Actions:
# # Log food
# # Remove last entry
# # Reporting?
#
# Goal:
# Manage mfp food log with minimum friction, thought, clicks or typing.
#
# Sample command lines:
# It's 3:30 pm and I just ate three egg whites. Log them to lunch:
# foodlog 3 white
# It's 3:30 pm and I ate a chopt spinach salad for lunch today. Log it to lunch:
# foodlog 1 chopt
# It's 3:30 pm and I remember I ate kashi and skim milk for breakfast today. Log their meal:
# foodlog b 1 kashi


import mechanicalsoup
import myfitnesspal_auth

login_url = "https://www.myfitnesspal.com/account/login"
login_post_url = "https://www.myfitnesspal.com/account/login"

br = mechanicalsoup.Browser()
br.set_debug_responses(True)
br.open(login_url)

br.select_form(nr=0)

control = br.form.find_control("username")
control.value = myfitnesspal_auth.username

control = br.form.find_control("password")
control.value = myfitnesspal_auth.password


response = br.submit()
print(response.info())
print(response.read())
