#!/bin/sh
#
# convert growlnotify command line parameters to terminal-notifier gem options
#
# pre-requisites:
# terminal-notifier gem (install with: gem install terminal-notifier --verbose --bindir=/usr/local/bin)
#
# sample growlnotify calls:
# git/docs//build/makefile.delegated:     @-growlnotify -n "mongodb-doc-build" -a "Terminal.app" -m build complete -t master stage
# git/docs//build/makefile.sphinx:        @-growlnotify -n "mongodb-doc-build" -a "Terminal.app" -m Sphinx -t Build in progress past critical phase.
# 
# sample terminal-notifier call:
#
# /usr/local/Cellar/ruby/1.9.3-p385/lib/ruby/gems/1.9.1/gems/terminal-notifier-1.4.2/bin/terminal-notifier -message 'message' -title 'title' -subtitle subtitle
#

message=""
title=""
subtitle="" # ignored
appname="" # ignored
iconapp="" # ignored

while [ "$1" ]
do
  if [ "$1" = "-n" ]
  then
    shift
    appname="$1"
    shift
  elif [ "$1" = "-a" ]
  then
    shift
    iconapp="$1"
    shift
  elif [ "$1" = "-m" ]
  then
    shift
    message="$1"
    shift
  elif [ "$1" = "-t" ]
  then
    shift
    title="$1"
    shift
  else
    # add a space if there's text in the title already 
    #
    if [ "$title" ]
    then
      title="$title "
    fi

    # add extra arguments to title
    #
    title="$title$1"
    shift
  fi
done
if [ "$message" ]
then
    terminal-notifier -message "$message" -title "$title" 
fi
