#!/bin/bash
#
# natgatewaylist
#
# List AWS nat gateways with caching. All arguments are case-insensitive grep patterns to filter by.
#
# Example:
# natgatewaylist prod
#
#
set -o nounset
set -o pipefail
set -o errexit

api_category="ec2"
api_call="describe-nat-gateways"
fields="NatGatewayId,VpcId,SubnetId,NatGatewayAddresses[].PublicIp"

aws_generic_list "$api_category" "$api_call" "$fields" "$@"
