#!/bin/bash
#
# Tell iTunes and Spotify to stop playing
#

if [ "`ps auwx | grep /iTunes.app/`" ]
then
    osascript -e 'tell application "iTunes" to stop'
fi
if [ "`ps auwx | grep /Spotify.app/`" ]
then
    osascript -e 'tell application "Spotify" to pause'
fi
