#!/bin/bash
#
# secretlist
#
# List secretsmanager secrets
#
# Example:
# secretlist sre
#
#
set -o nounset
#set -o pipefail
set -o errexit

function aws-get-profiles() {
   (
   grep \\[ ~/.aws/credentials ;
   grep \\[profile ~/.aws/config | sed 's/profile //'
   ) | tr -d [] | sort -u | sed 's/\#.*//g' | grep . | grep -v cloud-[a-z]*-[0-9]*$
}


DEFAULT_TIMEOUT=-1

if [ "${SECRETLIST_CACHE_TIMEOUT:-}" ]
then
  TIMEOUT="$SECRETLIST_CACHE_TIMEOUT"
else
  TIMEOUT="$DEFAULT_TIMEOUT"
fi

if [ ! "${AWS_PROFILE:-}" ]
then
  AWS_PROFILE=xgen-prod
fi

AWS_PROFILE=$AWS_PROFILE SECRETLIST_CACHE_TIMEOUT=$TIMEOUT aws_generic_list secretsmanager list-secrets Name "$@"
