#!/bin/bash
BGDIR=$HOME/bg
LOGFILE=/tmp/setbg.log

date >> "$LOGFILE"

if [ "$1" ]
then
  filename="$1"
else
  filename="`ls  \"$BGDIR/\"* | perl -e '@a=<>; print ($a[rand(@a)])' `"
fi

if [ "`uname`" = "Darwin" ]
then
  command="osascript -e \"tell application \\\"Finder\\\" to set desktop picture to POSIX file \\\"$filename\\\"\""
  
else
  command="gconftool-2 --type string --set /desktop/gnome/background/picture_filename \"$filename\""
fi

echo "$command" >> "$LOGFILE"
eval $command
