#!/bin/bash
#
# Loop infinitely, keeping an ssh connection open, restarting it if it exits
#

# Seconds to delay between connections
pause=5
while true
do
  args="$*"
  #echo "args: $args"
  if which xtitle >/dev/null 2>&1
    then
      xtitle ssh ${args/* /}
    fi
  date=$(date)
  ssh "$@"
  echo connected since: $date
  date
  echo sleeping $pause seconds
  sleep $pause
  date
done
