#!/bin/bash
#
# Loop infinitely, keeping an ssh connection open, restarting it if it exits
#
#
while true
do
  args="$*"
  #echo "args: $args"
  if which xtitle >/dev/null 2>&1
    then
      xtitle ssh ${args/* /}
    fi
  ssh "$@"
  sleep 5
  date
done
