#!/usr/bin/perl
# Parse a time and date string,
# convert to unix timestamp
#
use warnings;
use strict;
use Date::Parse;
my $time = str2time($ARGV[0]) || time;
print "$time\n";
print scalar localtime $time , "\n";

