#!/bin/sh
#
# Pull URL's out of input and verify them with HEAD HTTP requests
#
#
# Usage:
#
# cat <file> | urlcheck
#
# urlcheck <file>
#

if [ "$1" ]
then
  input="$1"
else
  input=-
fi

for url in $(cat $input | tr \)\(\[\]\  \\n | egrep https?: )
do
  echo "$url"
  curl --silent --head   "$url" | grep ^HT
done
