#!/bin/bash
#
# vpclist
#
# List VPC's with caching. All arguments are case-insensitive grep patterns to filter by.
#
# Example:
# vpclist vpc30
#
#
set -o nounset
set -o pipefail
set -o errexit

api_category="ec2"
api_call="describe-vpcs"
fields="VpcId,State,CidrBlock,IsDefault,Name"

aws_generic_list "$api_category" "$api_call" "$fields" "$@"
