#!/bin/bash
#
# vpclist
#
# List VPC's with caching. All arguments are case-insensitive grep patterns to filter by.
#
# Example:
# vpclist vpc30
#
#
set -o nounset
set -o pipefail
set -o errexit

thing_being_listed="vpc"
api_call="describe-vpcs"

awslist "$thing_being_listed" "$api_call" "$@"
